"""Unit + integration tests for the output guardrails.

Mirrors the existing test conventions (sys.path bootstrap +
``unittest.TestCase``). No network: each unit test calls the guardrail
function directly with synthetic input; integration tests monkeypatch
``run_agent_raw`` so no model is invoked.
"""

from __future__ import annotations

import asyncio
import json
import os
import sys
import unittest
from pathlib import Path
from typing import Any
from unittest.mock import patch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from agents import GuardrailFunctionOutput  # noqa: E402

import output_guardrails as g  # noqa: E402


# ─────────────────────────────────────────────────────────────────────────────
#  Helpers
# ─────────────────────────────────────────────────────────────────────────────


class _StubAgent:
    name = "stub-agent"


class _StubCtx:
    """Stand-in for RunContextWrapper. Only the .context attribute is read."""

    def __init__(self, context: Any = None) -> None:
        self.context = context


def _run(coro):
    return asyncio.get_event_loop().run_until_complete(coro)


def _valid_consensus_json() -> str:
    return json.dumps(
        {
            "primaryDiagnosis": "Migraine",
            "icdCode": "G43.909",
            "confidence": 82,
            "differentials": ["Tension headache", "Cluster headache"],
            "prognosis": "Good with proper management",
            "keyFindings": "Recurrent unilateral headache with photophobia",
            "urgency": "routine",
        }
    )


def _valid_plan_text() -> str:
    return """
## IMMEDIATE ACTIONS
Hydrate, rest in a dark room.

## MEDICATIONS TO CONSIDER
NSAID first-line; triptan if recurrent.

## DIAGNOSTIC TESTS
Consider MRI if red flags emerge.

## LIFESTYLE MODIFICATIONS
Sleep hygiene, regular meals, hydration.

## FOLLOW-UP SCHEDULE
2-week follow-up with neurology if symptoms persist.

## WARNING SIGNS
Sudden worst-ever headache, neurologic deficits.
"""


def _valid_message_text() -> str:
    return (
        "Thank you for sharing what you've been going through. After reviewing your "
        "symptoms, the most likely cause is migraine — a kind of headache that can "
        "feel overwhelming and is sometimes accompanied by sensitivity to light. "
        "Hydration, rest, and a quiet dark room often help. If your symptoms get "
        "worse or you notice any of the warning signs we've outlined, please act "
        "quickly. Remember, this guidance is generated by an AI advisory system and "
        "should not replace seeing your physician — please consult a licensed "
        "doctor before starting or changing treatment."
    )


# ─────────────────────────────────────────────────────────────────────────────
#  Consensus guardrail
# ─────────────────────────────────────────────────────────────────────────────


class ConsensusGuardrailTest(unittest.TestCase):
    def _check(self, raw: str) -> GuardrailFunctionOutput:
        return _run(g._check_consensus_output(_StubCtx(), _StubAgent(), raw))

    def test_valid_consensus_passes(self) -> None:
        result = self._check(_valid_consensus_json())
        self.assertFalse(result.tripwire_triggered)
        self.assertTrue(result.output_info.get("passed"))
        self.assertEqual(result.output_info["urgency"], "routine")

    def test_unparseable_trips(self) -> None:
        result = self._check("This is not JSON, just prose.")
        self.assertTrue(result.tripwire_triggered)
        self.assertEqual(result.output_info["code"], "consensus_unparseable")

    def test_bad_urgency_trips(self) -> None:
        bad = json.loads(_valid_consensus_json())
        bad["urgency"] = "asap"
        result = self._check(json.dumps(bad))
        self.assertTrue(result.tripwire_triggered)
        self.assertEqual(result.output_info["code"], "consensus_schema_invalid")

    def test_confidence_out_of_range_trips(self) -> None:
        bad = json.loads(_valid_consensus_json())
        bad["confidence"] = 150
        result = self._check(json.dumps(bad))
        self.assertTrue(result.tripwire_triggered)
        self.assertEqual(result.output_info["code"], "consensus_schema_invalid")

    def test_missing_required_field_trips(self) -> None:
        bad = json.loads(_valid_consensus_json())
        del bad["primaryDiagnosis"]
        result = self._check(json.dumps(bad))
        self.assertTrue(result.tripwire_triggered)
        self.assertEqual(result.output_info["code"], "consensus_schema_invalid")

    def test_bad_icd_format_trips(self) -> None:
        bad = json.loads(_valid_consensus_json())
        bad["icdCode"] = "MRI-Brain"
        result = self._check(json.dumps(bad))
        self.assertTrue(result.tripwire_triggered)
        self.assertEqual(result.output_info["code"], "consensus_icd_invalid")

    def test_empty_icd_lenient_default_passes(self) -> None:
        with patch.dict(os.environ, {"STRICT_ICD": ""}, clear=False):
            ok = json.loads(_valid_consensus_json())
            ok["icdCode"] = ""
            result = self._check(json.dumps(ok))
            self.assertFalse(result.tripwire_triggered)

    def test_empty_icd_strict_trips(self) -> None:
        with patch.dict(os.environ, {"STRICT_ICD": "1"}, clear=False):
            ok = json.loads(_valid_consensus_json())
            ok["icdCode"] = ""
            result = self._check(json.dumps(ok))
            self.assertTrue(result.tripwire_triggered)
            self.assertEqual(result.output_info["code"], "consensus_icd_invalid")

    def test_fenced_json_passes(self) -> None:
        fenced = "```json\n" + _valid_consensus_json() + "\n```"
        result = self._check(fenced)
        self.assertFalse(result.tripwire_triggered)


# ─────────────────────────────────────────────────────────────────────────────
#  Plan guardrail
# ─────────────────────────────────────────────────────────────────────────────


class PlanGuardrailTest(unittest.TestCase):
    def _check(self, text: str) -> GuardrailFunctionOutput:
        return _run(g._check_plan_structure(_StubCtx(), _StubAgent(), text))

    def test_all_six_headers_passes(self) -> None:
        result = self._check(_valid_plan_text())
        self.assertFalse(result.tripwire_triggered)
        self.assertEqual(len(result.output_info["found"]), 6)

    def test_five_of_six_passes(self) -> None:
        text = _valid_plan_text().replace("## MEDICATIONS TO CONSIDER", "")
        result = self._check(text)
        self.assertFalse(result.tripwire_triggered)

    def test_four_of_six_trips(self) -> None:
        text = (
            _valid_plan_text()
            .replace("## MEDICATIONS TO CONSIDER", "")
            .replace("## LIFESTYLE MODIFICATIONS", "")
        )
        result = self._check(text)
        self.assertTrue(result.tripwire_triggered)
        self.assertEqual(result.output_info["code"], "plan_structure_invalid")
        self.assertGreaterEqual(len(result.output_info["missing_headers"]), 2)

    def test_case_insensitive_match(self) -> None:
        text = _valid_plan_text().replace("## IMMEDIATE ACTIONS", "## immediate actions")
        result = self._check(text)
        self.assertFalse(result.tripwire_triggered)

    def test_trailing_colon_match(self) -> None:
        text = _valid_plan_text().replace(
            "## IMMEDIATE ACTIONS", "## IMMEDIATE ACTIONS:"
        )
        result = self._check(text)
        self.assertFalse(result.tripwire_triggered)


# ─────────────────────────────────────────────────────────────────────────────
#  Message guardrail
# ─────────────────────────────────────────────────────────────────────────────


class MessageGuardrailTest(unittest.TestCase):
    def _check(self, text: str, ctx_consensus: dict | None = None) -> GuardrailFunctionOutput:
        ctx = _StubCtx({"consensus": ctx_consensus} if ctx_consensus is not None else None)
        return _run(g._check_message(ctx, _StubAgent(), text))

    def test_disclaimer_at_end_passes(self) -> None:
        result = self._check(_valid_message_text())
        self.assertFalse(result.tripwire_triggered)

    def test_no_disclaimer_trips(self) -> None:
        text = (
            "Thanks for sharing your symptoms. The most likely cause is migraine. "
            "Hydrate, rest, and avoid bright lights. Take care."
        )
        result = self._check(text)
        self.assertTrue(result.tripwire_triggered)
        self.assertEqual(result.output_info["code"], "message_disclaimer_missing")

    def test_disclaimer_only_in_middle_trips(self) -> None:
        # AI/physician/consult mention is buried in the middle 70%; tail is bare.
        text = (
            "Thank you for reaching out. This is an AI advisory system — please "
            "consult your physician for any medical decisions. "
            + ("Now, about your symptoms: you described migraine-like episodes. " * 8)
            + "I hope you feel better soon."
        )
        result = self._check(text)
        self.assertTrue(result.tripwire_triggered)
        self.assertEqual(result.output_info["code"], "message_disclaimer_missing")

    def _disclaimer_tail(self) -> str:
        # Long enough to keep the AI/physician/consult tokens in the last 30%
        # of the full message even after a clinical paragraph is appended.
        return (
            " Remember, this guidance is generated by an AI advisory system and "
            "should not replace seeing your physician — please consult a "
            "licensed doctor before starting or changing treatment."
        )

    def test_hallucination_check_disabled_by_default(self) -> None:
        with patch.dict(os.environ, {"MESSAGE_HALLUCINATION_CHECK": ""}, clear=False):
            consensus = {
                "primaryDiagnosis": "Migraine",
                "differentials": ["Tension headache"],
            }
            body = "Thank you for sharing your symptoms. The team also considered fibrosis briefly."
            text = body + self._disclaimer_tail()
            result = self._check(text, ctx_consensus=consensus)
            # Default off — passes despite intruder term.
            self.assertFalse(result.tripwire_triggered)

    def test_hallucination_check_enabled_trips(self) -> None:
        with patch.dict(os.environ, {"MESSAGE_HALLUCINATION_CHECK": "1"}, clear=False):
            consensus = {
                "primaryDiagnosis": "Migraine",
                "differentials": ["Tension headache"],
            }
            # "fibrosis" matches the dx-token regex (-osis) and is not in consensus.
            body = "Thank you for sharing your symptoms. The team also considered fibrosis briefly."
            text = body + self._disclaimer_tail()
            result = self._check(text, ctx_consensus=consensus)
            self.assertTrue(result.tripwire_triggered)
            self.assertEqual(
                result.output_info["code"], "message_introduces_unknown_diagnosis"
            )

    def test_hallucination_check_enabled_consensus_terms_pass(self) -> None:
        with patch.dict(os.environ, {"MESSAGE_HALLUCINATION_CHECK": "1"}, clear=False):
            consensus = {
                "primaryDiagnosis": "Pulmonary fibrosis",
                "differentials": ["Sarcoidosis"],
            }
            body = (
                "Thank you for sharing your symptoms. The team weighed pulmonary "
                "fibrosis against sarcoidosis."
            )
            text = body + self._disclaimer_tail()
            result = self._check(text, ctx_consensus=consensus)
            self.assertFalse(result.tripwire_triggered)


class DisclaimerHelperTest(unittest.TestCase):
    def test_present_at_end(self) -> None:
        self.assertTrue(g._disclaimer_present(_valid_message_text()))

    def test_absent_when_buried(self) -> None:
        text = (
            "This is AI advice and you should consult your physician. "
            + ("Lorem ipsum dolor sit amet. " * 50)
        )
        self.assertFalse(g._disclaimer_present(text))


# ─────────────────────────────────────────────────────────────────────────────
#  Toxicity guardrail (with monkeypatched classifier)
# ─────────────────────────────────────────────────────────────────────────────


class ToxicityGuardrailTest(unittest.TestCase):
    def _check(self, output: str, classifier_response: str) -> GuardrailFunctionOutput:
        async def _fake_run_agent_raw(*args, **kwargs):
            return classifier_response

        # Make sure the lazy import inside the guardrail picks up our stub.
        import main as _main

        with patch.object(_main, "run_agent_raw", side_effect=_fake_run_agent_raw):
            return _run(g._check_toxicity(_StubCtx(), _StubAgent(), output))

    def test_safe_classifier_passes(self) -> None:
        result = self._check(
            "Patient has migraine; recommend hydration.",
            '{"is_safe": true, "category": "safe", "reasoning": "ok"}',
        )
        self.assertFalse(result.tripwire_triggered)

    def test_refusal_classifier_trips(self) -> None:
        result = self._check(
            "I cannot help with medical advice.",
            '{"is_safe": false, "category": "refusal", "reasoning": "refusal contradicts scope"}',
        )
        self.assertTrue(result.tripwire_triggered)
        self.assertEqual(result.output_info["code"], "toxicity_flagged")
        self.assertEqual(result.output_info["category"], "refusal")

    def test_classifier_error_passes_through(self) -> None:
        # If the classifier itself raises, don't block real output — pass with annotation.
        async def _boom(*args, **kwargs):
            raise RuntimeError("classifier infrastructure down")

        import main as _main

        with patch.object(_main, "run_agent_raw", side_effect=_boom):
            result = _run(g._check_toxicity(_StubCtx(), _StubAgent(), "Patient summary."))
        self.assertFalse(result.tripwire_triggered)
        self.assertIn("classifier_error", result.output_info)


# ─────────────────────────────────────────────────────────────────────────────
#  Integration: the FastAPI exception handler maps tripwires to 422 + structured detail
# ─────────────────────────────────────────────────────────────────────────────


class ExceptionHandlerTest(unittest.TestCase):
    """Exercise the FastAPI handler by raising the SDK exception directly.

    This avoids the cost of standing up the full pipeline; we only need to
    prove the @app.exception_handler is wired and shapes the response correctly.
    """

    def test_handler_returns_422_with_structured_detail(self) -> None:
        from fastapi.testclient import TestClient

        import main as _main

        # Create a tiny route that always raises the SDK tripwire so we can
        # observe the handler's response shape without invoking an LLM.
        # We piggyback onto the existing app by adding a probe route at runtime.
        from agents import OutputGuardrailTripwireTriggered
        from agents.guardrail import OutputGuardrailResult

        if "/_test/trip" not in {getattr(r, "path", "") for r in _main.app.router.routes}:
            @_main.app.get("/_test/trip")
            async def _probe():  # type: ignore[no-redef]
                # Build a minimal OutputGuardrailResult that mirrors a real trip.
                fake_output = GuardrailFunctionOutput(
                    output_info={
                        "failed_check": "schema",
                        "code": "consensus_schema_invalid",
                        "message": "test message",
                    },
                    tripwire_triggered=True,
                )
                fake_result = OutputGuardrailResult(
                    guardrail=g.consensus_output_guardrail,
                    agent_output="<raw>",
                    agent=_main.consensus_agent,
                    output=fake_output,
                )
                raise OutputGuardrailTripwireTriggered(fake_result)

        client = TestClient(_main.app)
        resp = client.get("/_test/trip")
        self.assertEqual(resp.status_code, 422)
        body = resp.json()
        self.assertEqual(body["detail"]["code"], "output_guardrail_failed")
        self.assertEqual(body["detail"]["subcode"], "consensus_schema_invalid")
        self.assertEqual(body["detail"]["guardrail"], "consensus_output_check")
        self.assertIn("Chen", body["detail"]["stage"])  # consensus agent name


if __name__ == "__main__":
    unittest.main()
